# WORK app
FROM node:15-alpine as app

# Copy source
COPY . /app

# Installing dependencies
RUN cd /app && yarn && yarn run build

# WORK main app
FROM node:15-alpine

# For start
COPY --from=app /app/.next /app/.next
COPY --from=app /app/node_modules /node_modules
COPY --from=app /app/package.json .

# Running the app
CMD yarn run start ./app